export const ADD_BOOKING = 'ADD_BOOKING';
export const UPDATE_ROOM_RESERVATION = 'UPDATE_ROOM_RESERVATION';
export const DELETE_ROOM_RESERVATION = 'DELETE_ROOM_RESERVATION';
export const SET_USER_BOOKINGS = 'SET_USER_BOOKINGS';
