export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const SEARCH_GAMES_SUCCESS = 'SEARCH_GAMES_SUCCESS';
export const GET_DISCOUNTED_GAMES_SUCCESS = 'GET_DISCOUNTED_GAMES_SUCCESS';
export const UPDATE_GAME_RESERVATION = 'UPDATE_GAME_RESERVATION';
export const DELETE_GAME_RESERVATION = 'DELETE_GAME_RESERVATION';
