export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const DELETE_ROOM_RESERVATION = 'DELETE_ROOM_RESERVATION';
export const UPDATE_ROOM_RESERVATION = 'UPDATE_ROOM_RESERVATION';
